services:
  - type: web
    name: playnowweb
    runtime: node
    plan: free
    buildCommand: npm install --production=false
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000